In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
z = np.array([3, 6, 9, 12, 15])

cov_matrix = np.cov([x, y, z])
print('\ncov_matrix:\n', cov_matrix)

cor_matrix = np.corrcoef([x, y, z])
print('\ncor_matrix:\n', cor_matrix)


cov_matrix:
 [[ 2.5  5.   7.5]
 [ 5.  10.  15. ]
 [ 7.5 15.  22.5]]

cor_matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
