In [6]:
import numpy as np

x1 = np.array([1, 2, 3, 4, 5])
x2 = np.array([2, 4, 6, 8, 10])
x3 = np.array([3, 6, 9, 12, 15])

print("\nnp.vstack([x1, x2, x3]):\n", np.vstack([x1, x2, x3]))

data = np.vstack([x1, x2, x3]).T

print("\ndata:\n", data)

cor_matrix = np.corrcoef(data, rowvar=False)

print('\ncor_matrix:\n', cor_matrix)

threshold = 0.7

print('\nVariables with high multicollinearity:\n')
for i in range(cor_matrix.shape[0]):
    for j in range(i+1, cor_matrix.shape[1]):
        if abs(cor_matrix[i, j]) > threshold:
            print(f"Variable {i+1} and variable {j+1}")


np.vstack([x1, x2, x3]):
 [[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]]

data:
 [[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]

cor_matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Variables with high multicollinearity:

Variable 1 and variable 2
Variable 1 and variable 3
Variable 2 and variable 3
